// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let PgResult = {};

async function transaction(client, callback) {
  await client.query("BEGIN");
  try {
    let result = await callback(client);
    await client.query("COMMIT");
    return result;
  } catch (exn) {
    await client.query("ROLLBACK");
    throw exn;
  }
}

let Client = {
  transaction: transaction
};

async function transaction$1(pool, callback) {
  let client = await pool.connect();
  try {
    let result = await transaction(client, callback);
    await client.release();
    return result;
  } catch (exn) {
    await client.release();
    throw exn;
  }
}

let Pool = {
  transaction: transaction$1
};

let Pg = {
  PgResult: PgResult,
  Client: Client,
  Pool: Pool
};

let IR = {};

let PreparedStatement = {};

exports.Pg = Pg;
exports.IR = IR;
exports.PreparedStatement = PreparedStatement;
/* No side effect */
