// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Pg = require("pg");

let PgResult = {};

async function transaction(client, callback) {
  await client.query("BEGIN");
  try {
    let result = await callback(client);
    await client.query("COMMIT");
    return result;
  } catch (exn) {
    await client.query("ROLLBACK");
    throw exn;
  }
}

let Client = {
  transaction: transaction
};

function make(config) {
  if (typeof config === "object") {
    return new Pg.Pool(config);
  } else {
    return new Pg.Pool({
      connectionString: config
    });
  }
}

async function transaction$1(pool, callback) {
  let client = await pool.connect();
  try {
    let result = await transaction(client, callback);
    client.release();
    return result;
  } catch (exn) {
    client.release();
    throw exn;
  }
}

let Pool = {
  make: make,
  transaction: transaction$1
};

let Pg$1 = {
  PgResult: PgResult,
  Client: Client,
  Pool: Pool
};

let IR = {};

let PreparedStatement = {};

exports.Pg = Pg$1;
exports.IR = IR;
exports.PreparedStatement = PreparedStatement;
/* pg Not a pure module */
